export const ao3Links = {
  work: "https://archiveofourown.org/works/76451261",
  firstChapter: "https://archiveofourown.org/works/76451261/chapters/200068196",
  latestChapter:
    "https://archiveofourown.org/works/76451261/chapters/212088806",
  latestComments:
    "https://archiveofourown.org/works/76451261/chapters/212088806#comments",
};

export const levels = [
  {
    id: 1,
    chapter: "Chapter 1",
    title: "Chapter 1",
    subtitle: "Restaurant robbery, apartment healing, patrol, and a night out.",
    sourceUrl: "https://archiveofourown.org/works/76451261/chapters/200068196",
    briefing:
      "Grian and Jimmy leave a restaurant robbery by Tekbox and Ethical, Gem heals Grian at the apartment, and Astraeus later joins the hero team on patrol.",
    objective: "Collect the chapter moments and push back the villains from Chapter 1.",
    completion: "Grian makes it through the restaurant, patrol, and a night out with friends.",
    zone: "Restaurant / Apartment / City Patrol",
    weather: "city night",
    accent: "#ff715b",
    ground: "#243047",
    sky: "#08111f",
    visual: {
      horizon: "#26152d",
      secondary: "#f8c75c",
      mist: "#ffad8d",
      particle: "#ffd0a8",
      portal: "#ff9276",
      ally: "#ffe7bd",
      enemy: "#3a1024",
      enemyAura: "#ff3d6e",
      skyline: "#111727",
      fogDensity: 0.058,
    },
    pickups: ["Back Door", "Pasta Dinner", "Hero Committee"],
    enemies: ["Tekbox", "Ethical", "Tithonus"],
    allies: ["Jimmy", "Gem", "Pearl", "Lizzie"],
  },
  {
    id: 2,
    chapter: "Chapter 2",
    title: "Chapter 2",
    subtitle: "Unexpected ICU shift, bank heist, broken ribs, and Aceso's disappearance.",
    sourceUrl: "https://archiveofourown.org/works/76451261/chapters/201097446",
    briefing:
      "Dr Ren moves Grian to an ICU shift, a bank heist pulls the heroes out, Moonlight badly injures Astraeus, and Aceso disappears.",
    objective: "Collect the chapter moments and survive the bank heist.",
    completion: "Astraeus leaves the hospital with broken ribs, and Aceso is still missing.",
    zone: "Hospital / Bank / Apartment",
    weather: "city night",
    accent: "#68e1fd",
    ground: "#233a42",
    sky: "#071923",
    visual: {
      horizon: "#0b3450",
      secondary: "#b9f7ff",
      mist: "#7bdff4",
      particle: "#d5fbff",
      portal: "#92ecff",
      ally: "#d8fbff",
      enemy: "#101c45",
      enemyAura: "#8d74ff",
      skyline: "#0d1a2b",
      fogDensity: 0.052,
    },
    pickups: ["ICU Shift", "Bank Heist", "Broken Ribs"],
    enemies: ["Moonlight", "Lucid", "Manic"],
    allies: ["Mumbo", "Jimmy", "Lizzie", "Pearl"],
  },
  {
    id: 3,
    chapter: "Chapter 3",
    title: "Chapter 3",
    subtitle: "Recovery, planning, the abandoned building, and Solo's healing.",
    sourceUrl: "https://archiveofourown.org/works/76451261/chapters/203917976",
    briefing:
      "While Grian recovers and Scar takes care of him, the heroes plan how to find Gem. They follow Lucid and Zero to an abandoned building, where Solo helps save Aceso.",
    objective: "Collect the chapter moments and rescue Aceso.",
    completion: "Solo saves Aceso, and the team gets her out alive.",
    zone: "Apartment / City Rooftops / Abandoned Building",
    weather: "quiet city night",
    accent: "#f8c75c",
    ground: "#2b2b3c",
    sky: "#130d28",
    visual: {
      horizon: "#2d174f",
      secondary: "#fff0a4",
      mist: "#f8c75c",
      particle: "#fff1b8",
      portal: "#ffd76f",
      ally: "#ffe9a8",
      enemy: "#2c184c",
      enemyAura: "#9d6cff",
      skyline: "#141326",
      fogDensity: 0.049,
    },
    pickups: ["Bed Rest", "Zero's Name", "Solo's Healing"],
    enemies: ["Tithonus", "Lucid"],
    allies: ["Jimmy", "Pearl", "Lizzie", "Solo"],
  },
  {
    id: 4,
    chapter: "Chapter 4",
    title: "Chapter 4",
    subtitle: "Gem's recovery, the hero meeting, Zero's name, and Grian and Scar.",
    sourceUrl: "https://archiveofourown.org/works/76451261/chapters/206472216",
    briefing:
      "Gem recovers at Pearl's house, the heroes meet at Jimmy's, Grian shares Zero's civilian name, and Grian and Scar finally admit how they feel.",
    objective: "Collect the chapter moments and reach the confession.",
    completion: "The team steadies itself, and Grian and Scar step into something more.",
    zone: "Pearl's House / Jimmy's House / Apartment",
    weather: "quiet night",
    accent: "#8ef0b3",
    ground: "#254237",
    sky: "#0b1c1a",
    visual: {
      horizon: "#17382f",
      secondary: "#ffdca8",
      mist: "#b8ffd2",
      particle: "#ddffe7",
      portal: "#adffd0",
      ally: "#fff0c8",
      enemy: "#211c30",
      enemyAura: "#b383ff",
      skyline: "#0f211d",
      fogDensity: 0.055,
    },
    pickups: ["Tomato Soup", "Hero Meeting", "Bdubs"],
    enemies: [],
    allies: ["Gem", "Pearl", "Jimmy", "Lizzie", "Scar"],
  },
  {
    id: 5,
    chapter: "Chapter 5",
    title: "Chapter 5",
    subtitle: "Office fire, patrol attack, hallucination, headquarters, and the cliffhanger.",
    sourceUrl: "https://archiveofourown.org/works/76451261/chapters/212088806",
    briefing:
      "Tekbox sets fire to an office building, Grian treats burn victims in the ER, patrol goes wrong, and Astraeus wakes in the villains' headquarters.",
    objective: "Collect the chapter moments and endure the villains' trap.",
    completion:
      "The chapter ends on a cliff edge. The next part of the story is still being written.",
    zone: "ER / Clockers Cafe / Alley / Villains' Headquarters",
    weather: "city night",
    accent: "#ff3d6e",
    ground: "#3f2532",
    sky: "#18050b",
    visual: {
      horizon: "#38101a",
      secondary: "#ff9f3d",
      mist: "#ff6a42",
      particle: "#ffb38b",
      portal: "#ff245c",
      ally: "#f8c75c",
      enemy: "#210811",
      enemyAura: "#ff174d",
      skyline: "#190912",
      fogDensity: 0.064,
    },
    pickups: ["Burn ICU", "Arrow Wound", "Villains' Headquarters"],
    enemies: ["Tekbox", "Moonlight", "Tithonus", "Cyclone", "Lucid", "Ethical", "Manic"],
    allies: ["Scar", "Gem", "Lizzie"],
    finalLevel: true,
  },
];

export const finale = {
  chapter: "Chapter 6",
  title: "Coming Soon",
  subtitle: "The next mission is still taking shape.",
};

export const vaultQuestions = [
  {
    prompt: "Which two villains wreck Grian and Jimmy's restaurant night?",
    options: ["Tekbox and Ethical", "Two unnamed thieves", "A different villain pair"],
    answer: "Tekbox and Ethical",
  },
  {
    prompt: "Who patches Grian up after Tekbox burns him?",
    options: ["Gem", "Pearl", "Scar"],
    answer: "Gem",
  },
  {
    prompt: "What does Grian cook for Scar, somehow forgetting the most important part?",
    options: ["Pasta", "Tomato soup", "Ramen noodles"],
    answer: "Pasta",
  },
];
